# Generated by Django 4.2.1 on 2023-06-11 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RanksClasses', '0002_creatureclass'),
        ('Enemies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RanksClasses.creaturerank'),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RanksClasses.creatureclass'),
        ),
    ]
