# Generated by Django 4.2.1 on 2023-06-13 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Regions', '0001_initial'),
        ('RanksClasses', '0002_creatureclass'),
        ('Enemies', '0003_enemy_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enemies', to='RanksClasses.creaturerank'),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enemies', to='Regions.region'),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enemies', to='RanksClasses.creatureclass'),
        ),
    ]
