# Generated by Django 4.2.1 on 2023-06-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RanksClasses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatureClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=1, unique=True)),
                ('name', models.CharField(max_length=12, unique=True)),
            ],
        ),
    ]
