# Generated by Django 4.2.1 on 2023-06-07 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RanksClasses', '0001_initial'),
        ('Characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RanksClasses.rank'),
        ),
    ]
