# Generated by Django 4.2.1 on 2023-06-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0004_ability_agility_ability_attack_ability_defense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='heal_percent',
        ),
        migrations.RemoveField(
            model_name='aspect',
            name='heal_percent',
        ),
        migrations.RemoveField(
            model_name='flaw',
            name='heal_percent',
        ),
    ]
