# Generated by Django 4.2.1 on 2023-06-14 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Regions', '0001_initial'),
        ('Characters', '0007_remove_ability_description_remove_aspect_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='Regions.region'),
        ),
    ]
