# Generated by Django 4.2.1 on 2023-06-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0008_character_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='hp',
            field=models.IntegerField(default=100),
        ),
    ]
